### ISSUE TITLE
工具栏的长按显示bug

### ISSUE THREAD

**Issue by Entaligaa** [ZhuJHua/moodiary#12]
![Screenshot_20241019_122430_cn.yooss.moodiary_edit_2048581901255638.jpg](https://github.com/user-attachments/assets/074e5bce-6570-492c-9b46-b3f261d680a7)

![Screenshot_20241019_122434_cn.yooss.moodiary_edit_2048569927960848.jpg](https://github.com/user-attachments/assets/04c1fb9b-236b-4387-8d65-5d6881316a25)

会被输入法挡住

手机：mate40pro
系统：鸿蒙4.2

**Comment by ZhuJHua** [comment]
之前的问题解决了吗？我手上没有鸿蒙设备🥲没办法测试。

**Comment by Entaligaa** [comment]
> 之前的问题解决了吗？我手上没有鸿蒙设备🥲没办法测试。

全解决了，大佬厉害
