### ISSUE TITLE
希望可以记录位置信息

### ISSUE THREAD

**Issue by Entaligaa** [ZhuJHua/moodiary#13]
![Screenshot_20241019_123526_com.huawei.photos.jpg](https://github.com/user-attachments/assets/31dadb9a-d509-4928-8507-bc06eee55552)

感觉像这样很有一种满足感
（虽然我不是那种总有时间去旅游，然后天天记录的人🫣）

**Comment by Entaligaa** [comment]
就只是感觉有意思，作者也不要因此打断自己的开发节奏啦

**Comment by ZhuJHua** [comment]
![image](https://github.com/user-attachments/assets/837b8a9a-b043-4466-991b-87c849f9dc05)
跟进一下，马上会上

**Comment by ZhuJHua** [comment]
https://github.com/user-attachments/assets/b7c3c49f-e762-4b84-be4e-4dc2fa660523
