### ISSUE TITLE
编辑-更多-分类界面中，无法移出分类

### ISSUE THREAD

**Issue by Entaligaa** [ZhuJHua/moodiary#14]
![Screenshot_20241019_171511_cn.yooss.moodiary_edit_2064541934919869.jpg](https://github.com/user-attachments/assets/2c21627f-43c0-4a8b-9861-5dc3baa8eacc)

比如说我不想给今天的记录打标签（很奇怪hh），但我没法给他移出来

作者可以添加一个再次点击来取消分类吗

**Comment by ZhuJHua** [comment]
分类和标签是不一样的，分类是一类日记的整合，分类是在设置-管理-分类中集中管理的，编辑页面是为了方便撰写第一篇该分类下的目录才加上添加功能的，更多分类的管理要在设置中进行。如果你只是想给单篇日记加一个tag，可以用标签来组织。

**Comment by ZhuJHua** [comment]
一篇日记只能属于一个分类（默认是无分类），但是可以拥有多个标签

**Comment by ZhuJHua** [comment]
这里显示两个是因为你总共有两个分类可供选择

**Comment by ZhuJHua** [comment]
奥，我好像误会你的意思了，你的意思是说不小心选了分类，然后不想分类了是吧，等我加一个默认分类的选项。😣

**Comment by Entaligaa** [comment]
> 奥，我好像误会你的意思了，你的意思是说不小心选了分类，然后不想分类了是吧，等我加一个默认分类的选项。😣

yes，辛苦大佬了！😘
