### ISSUE TITLE
Windows端无法导出出来

### ISSUE THREAD

**Issue by lightoalawliet** [ZhuJHua/moodiary#20]
日记写了有一段时间，当想导出出来的时候会提示：“我们无法为你显示所有共享方法”，剩下的区域一片空白，没有其它可操作的选项，也就是说导出不出来，作者可以看一下目前出现在Windows端无法导出的这个问题。
如下是配图：

[![moodiary.jpg](https://i.postimg.cc/mDDzZSJQ/moodiary.jpg)](https://postimg.cc/2qs82nz6)

**Comment by ZhuJHua** [comment]
今天我排查一下
