### ISSUE TITLE
[Feature]关于日记编辑

### ISSUE THREAD

**Issue by aglorice** [ZhuJHua/moodiary#28]
## 💡 新功能请求 | Feature Request
可不可以针对日记编辑，在增加录音和图片和视频的时候可以允许用户自由插入想录音，图片，视频，功能选项从原来的更多放到原富文本编辑器上的菜单栏上，直接可以在想插入的时候插入。😍

A clear and concise description of the feature you'd like to be added.

## 🤔 这个功能能解决什么问题？| What problem does this feature solve?

很有必要，极大的提高了自由度和整体编辑体验.

Explain why this feature would be useful or what problem it solves.

## 📑 实现细节（可选）| Implementation Details (optional)

![Image_1730342838719](https://github.com/user-attachments/assets/a5202b85-fafe-4521-89db-2fd385617e22)

If you have any ideas on how to implement it, please provide details.

## 📱 相关设备/平台 | Relevant Devices/Platforms

- 平台: [e.g. iOS/Android]
- 相关版本: [e.g. v1.0.0]

## 🗒️ 其他信息 | Additional context

关于此功能的其他信息。

**Comment by ZhuJHua** [comment]
你指的是图文混排吗，现在图文是单独处理的

**Comment by aglorice** [comment]
对

**Comment by ZhuJHua** [comment]
有时间我会看看

**Comment by ZhuJHua** [comment]
这周内会做好
https://github.com/user-attachments/assets/94bb3568-6abf-403e-b3fc-c8938207e40e
