### ISSUE TITLE
希望增加webdav备份

### ISSUE THREAD

**Issue by Entaligaa** [ZhuJHua/moodiary#30]

**Comment by ZhuJHua** [comment]
这周会发一个新版，包括地图和局域网同步，最近工作有点忙不好意思😢

**Comment by Entaligaa** [comment]
> 这周会发一个新版，包括地图和局域网同步，最近工作有点忙不好意思😢

太感谢了！作者你效率真高

**Comment by ZhuJHua** [comment]
![ce17fb54b6b869937cc804144496cc6e](https://github.com/user-attachments/assets/bbdd46f0-e1da-4a34-8682-a5da22b44141)

**Comment by Entaligaa** [comment]
❤
