### ISSUE TITLE
[BUG]无法在应用内更改ai的api

### ISSUE THREAD

**Issue by OneBird2018** [ZhuJHua/moodiary#31]
## 🐛 Bug 描述 | Bug Description

无法在应用内更改ai的api，意味着必须手动编译才能使用

## 📱 设备信息 | Device Information

- 操作系统: Android
- 设备型号: oppo A3

**Comment by ZhuJHua** [comment]
是的，这个已经修复了，今天晚些时候我会发布一个新版本

**Comment by OSNewbie** [comment]
> 是的，这个已经修复了，今天晚些时候我会发布一个新版本

AI上我是担心一点点小问题？
所以想请作者回答一下，回答我的顾虑

你说AI是本地模型，我也不清楚，可能是调用腾讯云那个key  我不清楚他是否会收集数据做模型训练
我主要是担心日记上面的内容，AI读取后是否有风险？，

至于想改善措施，要么就做个隐私笔记的一个访问功能限制，就是可能设置密码或者别的
就是不让AI读取或者回答，

**Comment by ZhuJHua** [comment]
> > 是的，这个已经修复了，今天晚些时候我会发布一个新版本
> 
> AI上我是担心一点点小问题？
> 所以想请作者回答一下，回答我的顾虑
> 
> 你说AI是本地模型，我也不清楚，可能是调用腾讯云那个key  我不清楚他是否会收集数据做模型训练
> 我主要是担心日记上面的内容，AI读取后是否有风险？，
> 
> 至于想改善措施，要么就做个隐私笔记的一个访问功能限制，就是可能设置密码或者别的
> 就是不让AI读取或者回答，

嗨，关于ai的问题，我不会也不能把你的日记发送给第三方ai，目前发送给第三方ai的只有你的心情数据

**Comment by DHS1001** [comment]
是否有可能支持自建的AI模型？谢谢啦
