### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Entaligaa** [ZhuJHua/moodiary#36]
删除日记需要重新载入app，才显示删除成功

（新版本bug貌似，还有就是我才意识到一直以来没删过日记。。。

**Comment by ZhuJHua** [comment]
是重构时忘记改了，现在修

**Comment by Entaligaa** [comment]
> 是重构时忘记改了，现在修

那行，那我先不到处点点点了😄

**Comment by ZhuJHua** [comment]
芭比Q了，好像有点严重，我把深拷贝改成浅拷贝了，脑子抽了，到处都是bug

**Comment by Entaligaa** [comment]
> 芭比Q了，好像有点严重，我把深拷贝改成浅拷贝了，脑子抽了，到处都是bug

hh作者你人太好了，按您的节奏来就行，我们都是你无私奉献的享受者😸
