### ISSUE TITLE
似乎没有自定义日记存储路径的功能

### ISSUE THREAD

**Issue by Entaligaa** [ZhuJHua/moodiary#37]
比方说我想把日记放在Documents里面

**Comment by ZhuJHua** [comment]
这个暂时先没有，现在路径就是默认路径，默认路径是app的support目录，正常是看不到的（文件管理器中）。这样做的原因是：
1.比较安全，一般的第三方软件读取不到（漏洞或者root了的设备除外）
2.比较方便些，因为申请目录需要权限，有些用户可能对文件权限比较敏感，其实你可以注意到在软件内是没有申请过文件或者照片权限的

其实理论上自定义目录是可以实现的，因为现在文件的路径都是在app打开时确定的

**Comment by Entaligaa** [comment]
> 这个暂时先没有，现在路径就是默认路径，默认路径是app的support目录，正常是看不到的（文件管理器中）。这样做的原因是：
> 1.比较安全，一般的第三方软件读取不到（漏洞或者root了的设备除外）
> 2.比较方便些，因为申请目录需要权限，有些用户可能对文件权限比较敏感，其实你可以注意到在软件内是没有申请过文件或者照片权限的
> 
> 其实理论上自定义目录是可以实现的，因为现在文件的路径都是在app打开时确定的

👌，了解了
