### ISSUE TITLE
[BUG] 软件无法正常进入

### ISSUE THREAD

**Issue by AcardiaX** [ZhuJHua/moodiary#65]
## 🐛 Bug 描述 | Bug Description

- 软件无法正常进入，怀疑是系统问题

## 📱 设备信息 | Device Information

- 操作系统: [MagicOS_8.0，Android_14]
- 设备型号: [荣耀100 MAA-AN00]
- App 版本: [v2.6.0]

## 🖼️ 截图 | Screenshots

![Image_1733921728899](https://github.com/user-attachments/assets/cd0e98dc-aca5-4af1-9897-2b27f4024fe9)

![IMG_20241211_210536](https://github.com/user-attachments/assets/e6d711dd-3e89-458c-b1da-4e4bf3e6d4a9)

**Comment by ZhuJHua** [comment]
具体表现是什么呢？点击后没反应吗

**Comment by ZhuJHua** [comment]
可以加一下qq群，在群里说吧

**Comment by AcardiaX** [comment]
> 具体表现是什么呢？点击后没反应吗

是的 点击开始就会提示错误
