### ISSUE TITLE
大佬好!  日历时间线 那边的过滤 能否增加个全部的选项

### ISSUE THREAD

**Issue by lanyu96** [ZhuJHua/moodiary#72]
## 💡 新功能请求 | Feature Request

时间线页签的过滤增加全部选项, 选择全部后, 不按照选择的具体日过滤 , 可以看到所有的,  如果数据过多 ,通过上拉加载更多

## 🤔 这个功能能解决什么问题？| What problem does this feature solve?

时间线这个功能做的非常好,    但是时间线也可以用来总览或者说是沉浸式的浏览一段时间记录的内容 ,  所以我认为去掉时间线的过滤功能还是有必要的

**Comment by ZhuJHua** [comment]
嗨，感谢你的建议，时间线会在下个版本优化😃
