### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Dazengx** [ZhuJHua/moodiary#74]
很好用的软件，已经点亮小星星。
希望能增加对 Markdown 的支持，
希望能增加导入 Markdown 文件。

**Comment by ZhuJHua** [comment]
嗨，感谢你建议，我现在使用的编辑器是 Quill ，具体可以看 https://quilljs.com/ ，和 markdown 不属于同一类，关于对 markdown 的支持，可能还要有一段时间。
