### ISSUE TITLE
作者大大未来会添加自定义位置与天气功能吗

### ISSUE THREAD

**Issue by Entaligaa** [ZhuJHua/moodiary#8]
如题

**Comment by ZhuJHua** [comment]
之前有考虑过自定义位置或者天气，没有采用的原因是天气种类太多了，像用的天气图标库里面有几百种图标，如果做成选项式的话可能不会太好。

**Comment by Entaligaa** [comment]
> 之前有考虑过自定义位置或者天气，没有采用的原因是天气种类太多了，像用的天气图标库里面有几百种图标，如果做成选项式的话可能不会太好。

原来如此，了解了
