### ISSUE TITLE
[BUG]天地图已经停止注册个人开发者

### ISSUE THREAD

**Issue by Free-Aaron-Li** [ZhuJHua/moodiary#90]
## 🐛 Bug 描述 | Bug Description

天地图已经停止注册个人开发者。

## 📝 复现步骤 | Steps to Reproduce

登陆天地图开发拼图，发现无法注册个人开发者，无法调用API。

## 🤔 预期行为 | Expected behavior

A clear description of what you expected to happen.

## 📱 设备信息 | Device Information

- 操作系统: [Android]
- App 版本: [2.6.4]

## 🖼️ 截图 | Screenshots

![图片](https://github.com/user-attachments/assets/863d461b-049a-4a25-87fe-f38c9615e39c)

**Comment by ZhuJHua** [comment]
不应该啊，你再试试

**Comment by Free-Aaron-Li** [comment]
ok,是我错了。天气云无需详细信息，直接注册即可。
